volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:18@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
