volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:18@sha256:32ca0af8e77bfb8c6610c488e4691f83f972a3e9e64d3b02facf3ab111ad5500
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
