volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:18@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
